package ru.stqa.pft.litecart;// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.annotations.AfterMethod;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class LitecartTest {
  FirefoxDriver wd;

  @BeforeMethod
  public void setUp() {
    wd = new FirefoxDriver();
    wd.manage().timeouts().implicitlyWait(60,TimeUnit.SECONDS);
  }
  @AfterMethod
  public void tearDown() {
    wd.quit();
  }
  @Test
  public void litecartTest() {
    wd.get("http://localhost/litecart/en/");
    wd.manage().window().setSize(new Dimension(927, 703));
    wd.findElement(By.linkText("New customers click here")).click();
    wd.findElement(By.name("firstname")).click();
    wd.findElement(By.name("firstname")).sendKeys("Test");
    wd.findElement(By.name("lastname")).click();
    wd.findElement(By.name("lastname")).sendKeys("TestTest");
    wd.findElement(By.name("address1")).click();
    wd.findElement(By.name("address1")).click();
    wd.findElement(By.name("address1")).sendKeys("Test");
    wd.findElement(By.name("address2")).click();
    wd.findElement(By.name("address2")).sendKeys("Test");
    wd.findElement(By.name("postcode")).click();
    wd.findElement(By.name("postcode")).sendKeys("111222");
    wd.findElement(By.name("city")).click();
    wd.findElement(By.name("city")).sendKeys("Moscow");
    wd.findElement(By.name("email")).click();
    wd.findElement(By.name("email")).sendKeys("prosto_9090@bk.ru");
    wd.findElement(By.name("phone")).click();
    wd.findElement(By.name("phone")).sendKeys("+78889995566");
    wd.findElement(By.name("password")).click();
    wd.findElement(By.name("password")).sendKeys("Bylerwbz123");
    wd.findElement(By.name("confirmed_password")).click();
    wd.findElement(By.name("confirmed_password")).sendKeys("Bylerwbz123");
    wd.findElement(By.name("captcha")).click();
    wd.findElement(By.name("captcha")).sendKeys("6669");
    wd.findElement(By.name("create_account")).click();
  }
}
